"""criar_tabela_financials

Revision ID: 024edc4635bc
Revises: da159abefe02
Create Date: 2025-07-23 17:59:40.118534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '024edc4635bc'
down_revision = 'da159abefe02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('banco', sa.Integer(), nullable=False),
    sa.Column('agencia', sa.String(length=10), nullable=False),
    sa.Column('conta', sa.String(length=15), nullable=False),
    sa.Column('tipo_conta', sa.String(length=20), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=20), nullable=False),
    sa.Column('tipo_chave_pix', sa.String(length=20), nullable=False),
    sa.Column('chave_pix', sa.String(length=50), nullable=False),
    sa.Column('preferencia', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financials_id'), 'financials', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financials_id'), table_name='financials')
    op.drop_table('financials')
    # ### end Alembic commands ### 