"""criar_tabela_interests

Revision ID: 09931ddc1d0e
Revises: ee2dcd78f11e
Create Date: 2025-07-23 20:48:48.223373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09931ddc1d0e'
down_revision = 'ee2dcd78f11e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id_interessado', sa.Integer(), nullable=False),
    sa.Column('profile_id_interesse', sa.Integer(), nullable=False),
    sa.Column('data_inicial', sa.Date(), nullable=False),
    sa.Column('horario_inicial', sa.String(length=5), nullable=False),
    sa.Column('duracao_apresentacao', sa.Float(), nullable=False),
    sa.Column('valor_hora_ofertado', sa.Float(), nullable=False),
    sa.Column('valor_couvert_ofertado', sa.Float(), nullable=False),
    sa.Column('space_event_type_id', sa.Integer(), nullable=True),
    sa.Column('space_festival_type_id', sa.Integer(), nullable=True),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('resposta', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('AGUARDANDO_CONFIRMACAO', 'ACEITO', 'RECUSADO', name='statusinterest'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id_interessado'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['profile_id_interesse'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['space_event_type_id'], ['space_event_types.id'], ),
    sa.ForeignKeyConstraint(['space_festival_type_id'], ['space_festival_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interests_id'), 'interests', ['id'], unique=False)
    op.create_index(op.f('ix_interests_profile_id_interessado'), 'interests', ['profile_id_interessado'], unique=False)
    op.create_index(op.f('ix_interests_profile_id_interesse'), 'interests', ['profile_id_interesse'], unique=False)
    op.create_index(op.f('ix_interests_status'), 'interests', ['status'], unique=False)
    op.drop_index('ix_financials_temp_id', table_name='financials')
    op.create_index(op.f('ix_financials_id'), 'financials', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financials_id'), table_name='financials')
    op.create_index('ix_financials_temp_id', 'financials', ['id'], unique=False)
    op.drop_index(op.f('ix_interests_status'), table_name='interests')
    op.drop_index(op.f('ix_interests_profile_id_interesse'), table_name='interests')
    op.drop_index(op.f('ix_interests_profile_id_interessado'), table_name='interests')
    op.drop_index(op.f('ix_interests_id'), table_name='interests')
    op.drop_table('interests')
    # ### end Alembic commands ### 