"""criar_tabela_cep_coordinates

Revision ID: 0f9228074c43
Revises: 6a3d349eb6db
Create Date: 2025-07-24 20:33:14.130774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f9228074c43'
down_revision = '6a3d349eb6db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cep_coordinates',
    sa.Column('cep', sa.String(length=9), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('logradouro', sa.String(length=200), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('cep')
    )
    op.create_index('idx_cep_coordinates_cidade_uf', 'cep_coordinates', ['cidade', 'uf'], unique=False)
    op.create_index('idx_cep_coordinates_lat_lng', 'cep_coordinates', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_cep_coordinates_cep'), 'cep_coordinates', ['cep'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cep_coordinates_cep'), table_name='cep_coordinates')
    op.drop_index('idx_cep_coordinates_lat_lng', table_name='cep_coordinates')
    op.drop_index('idx_cep_coordinates_cidade_uf', table_name='cep_coordinates')
    op.drop_table('cep_coordinates')
    # ### end Alembic commands ### 