"""criar_tabela_space_types

Revision ID: 3c41237bb0cf
Revises: ea13875a1a10
Create Date: 2025-07-22 17:10:25.959489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c41237bb0cf'
down_revision = 'ea13875a1a10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('space_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_space_types_id'), 'space_types', ['id'], unique=False)
    op.create_index(op.f('ix_space_types_tipo'), 'space_types', ['tipo'], unique=True)
    op.drop_table('artist_musical_style')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_musical_style',
    sa.Column('artist_id', sa.INTEGER(), nullable=False),
    sa.Column('musical_style_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['musical_style_id'], ['musical_styles.id'], ),
    sa.PrimaryKeyConstraint('artist_id', 'musical_style_id')
    )
    op.drop_index(op.f('ix_space_types_tipo'), table_name='space_types')
    op.drop_index(op.f('ix_space_types_id'), table_name='space_types')
    op.drop_table('space_types')
    # ### end Alembic commands ### 