"""criar_tabela_artists

Revision ID: 414224c966f5
Revises: 53404b0ea99e
Create Date: 2025-07-21 13:37:37.465583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '414224c966f5'
down_revision = '53404b0ea99e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('artist_type_id', sa.Integer(), nullable=False),
    sa.Column('dias_apresentacao', sa.String(), nullable=False),
    sa.Column('raio_atuacao', sa.Float(), nullable=False),
    sa.Column('duracao_apresentacao', sa.Float(), nullable=False),
    sa.Column('valor_hora', sa.Float(), nullable=False),
    sa.Column('valor_couvert', sa.Float(), nullable=False),
    sa.Column('requisitos_minimos', sa.String(), nullable=False),
    sa.Column('instagram', sa.String(), nullable=True),
    sa.Column('tiktok', sa.String(), nullable=True),
    sa.Column('youtube', sa.String(), nullable=True),
    sa.Column('facebook', sa.String(), nullable=True),
    sa.Column('soundcloud', sa.String(), nullable=True),
    sa.Column('bandcamp', sa.String(), nullable=True),
    sa.Column('spotify', sa.String(), nullable=True),
    sa.Column('deezer', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['artist_type_id'], ['artist_types.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id')
    )
    op.create_index(op.f('ix_artists_id'), 'artists', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artists_id'), table_name='artists')
    op.drop_table('artists')
    # ### end Alembic commands ### 