"""add user_id to profiles

Revision ID: 68f6f035ed6c
Revises: 43c66d055b19
Create Date: 2025-07-21 11:02:26.428723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68f6f035ed6c'
down_revision = '43c66d055b19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import Column, Integer, ForeignKey
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(Column('user_id', Integer, nullable=False))
        batch_op.create_foreign_key('fk_profiles_user_id_users', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_profiles_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')
    # ### end Alembic commands ### 