"""adicionar_coluna_status_em_space_festival_types

Revision ID: 6a3d349eb6db
Revises: fac0bf1cfd90
Create Date: 2025-07-24 10:17:45.664930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a3d349eb6db'
down_revision = 'fac0bf1cfd90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Para SQLite, adicionar diretamente como não nullable com valor padrão
    op.add_column('space_festival_types', sa.Column('status', sa.Enum('CONTRATANDO', 'FECHADO', 'SUSPENSO', 'CANCELADO', name='statusfestivaltype'), nullable=False, server_default='CONTRATANDO'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('space_festival_types', 'status')
    # ### end Alembic commands ### 