"""criar_tabela_bookings

Revision ID: 78624315ea0c
Revises: b9b056978a56
Create Date: 2025-07-23 11:11:01.462721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78624315ea0c'
down_revision = 'b9b056978a56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('profile_id', sa.Integer(), nullable=False),
        sa.Column('data_inicio', sa.DateTime(timezone=True), nullable=False),
        sa.Column('horario_inicio', sa.String(length=50), nullable=False),
        sa.Column('data_fim', sa.DateTime(timezone=True), nullable=False),
        sa.Column('horario_fim', sa.String(length=50), nullable=False),
        sa.Column('space_id', sa.Integer(), nullable=True),
        sa.Column('artist_id', sa.Integer(), nullable=True),
        sa.Column('space_event_type_id', sa.Integer(), nullable=True),
        sa.Column('space_festival_type_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.current_timestamp(), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.current_timestamp(), nullable=True),
        sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
        sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
        sa.ForeignKeyConstraint(['space_event_type_id'], ['space_event_types.id'], ),
        sa.ForeignKeyConstraint(['space_festival_type_id'], ['space_festival_types.id'], ),
        sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ### 