"""criar_tabela_artist_musical_style

Revision ID: 8c609b94bc3a
Revises: 414224c966f5
Create Date: 2025-07-22 08:30:49.231561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c609b94bc3a'
down_revision = '414224c966f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 