"""criar tabela festival_types

Revision ID: 8e9b6f6945f6
Revises: 0725968ffc4c
Create Date: 2025-07-22 18:37:19.660798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e9b6f6945f6'
down_revision = '0725968ffc4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('festival_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_festival_types_id'), 'festival_types', ['id'], unique=False)
    op.create_index(op.f('ix_festival_types_type'), 'festival_types', ['type'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_festival_types_type'), table_name='festival_types')
    op.drop_index(op.f('ix_festival_types_id'), table_name='festival_types')
    op.drop_table('festival_types')
    # ### end Alembic commands ### 