"""criar_tabela_space_festival_types

Revision ID: b9b056978a56
Revises: c74a93c4825a
Create Date: 2024-12-19 11:15:23.123456

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b9b056978a56'
down_revision = 'c74a93c4825a'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('space_festival_types',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('space_id', sa.Integer(), nullable=False),
        sa.Column('festival_type_id', sa.Integer(), nullable=False),
        sa.Column('tema', sa.String(length=200), nullable=False),
        sa.Column('descricao', sa.Text(), nullable=False),
        sa.Column('link_divulgacao', sa.String(length=500), nullable=True),
        sa.Column('banner', sa.String(length=500), nullable=True),
        sa.Column('data', sa.DateTime(timezone=True), nullable=False),
        sa.Column('horario', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.current_timestamp(), nullable=True),
        sa.ForeignKeyConstraint(['festival_type_id'], ['festival_types.id'], ),
        sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_space_festival_types_id'), 'space_festival_types', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_space_festival_types_id'), table_name='space_festival_types')
    op.drop_table('space_festival_types')
    # ### end Alembic commands ### 