"""criar tabela spaces

Revision ID: c96d7ef6f3f3
Revises: 8e9b6f6945f6
Create Date: 2025-07-22 21:01:31.037202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c96d7ef6f3f3'
down_revision = '8e9b6f6945f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('space_type_id', sa.Integer(), nullable=False),
    sa.Column('event_type_id', sa.Integer(), nullable=True),
    sa.Column('festival_type_id', sa.Integer(), nullable=True),
    sa.Column('acesso', sa.String(), nullable=False),
    sa.Column('dias_apresentacao', sa.JSON(), nullable=False),
    sa.Column('duracao_apresentacao', sa.Float(), nullable=False),
    sa.Column('valor_hora', sa.Float(), nullable=False),
    sa.Column('valor_couvert', sa.Float(), nullable=False),
    sa.Column('requisitos_minimos', sa.Text(), nullable=False),
    sa.Column('oferecimentos', sa.Text(), nullable=False),
    sa.Column('estrutura_apresentacao', sa.Text(), nullable=False),
    sa.Column('publico_estimado', sa.String(), nullable=False),
    sa.Column('fotos_ambiente', sa.JSON(), nullable=False),
    sa.Column('instagram', sa.String(), nullable=True),
    sa.Column('tiktok', sa.String(), nullable=True),
    sa.Column('youtube', sa.String(), nullable=True),
    sa.Column('facebook', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_types.id'], ),
    sa.ForeignKeyConstraint(['festival_type_id'], ['festival_types.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['space_type_id'], ['space_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spaces_id'), 'spaces', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spaces_id'), table_name='spaces')
    op.drop_table('spaces')
    # ### end Alembic commands ### 