"""criar_tabela_artist_musical_style_manual

Revision ID: ea13875a1a10
Revises: 8c609b94bc3a
Create Date: 2025-07-22 08:40:10.566642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea13875a1a10'
down_revision = '8c609b94bc3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_musical_style',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('musical_style_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['musical_style_id'], ['musical_styles.id'], ),
    sa.PrimaryKeyConstraint('artist_id', 'musical_style_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artist_musical_style')
    # ### end Alembic commands ### 