"""alterar_coluna_banco_para_string

Revision ID: ee2dcd78f11e
Revises: 024edc4635bc
Create Date: 2025-07-23 18:56:14.543048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee2dcd78f11e'
down_revision = '024edc4635bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Para SQLite, precisamos recriar a tabela completa
    connection = op.get_bind()
    
    # 1. Criar tabela temporária com estrutura nova
    op.create_table('financials_temp',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('profile_id', sa.Integer(), sa.ForeignKey('profiles.id'), nullable=False),
        sa.Column('banco', sa.String(length=3), nullable=False),
        sa.Column('agencia', sa.String(length=10), nullable=False),
        sa.Column('conta', sa.String(length=15), nullable=False),
        sa.Column('tipo_conta', sa.String(length=20), nullable=False),
        sa.Column('cpf_cnpj', sa.String(length=20), nullable=False),
        sa.Column('tipo_chave_pix', sa.String(length=20), nullable=False),
        sa.Column('chave_pix', sa.String(length=50), nullable=False),
        sa.Column('preferencia', sa.String(length=10), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now())
    )
    
    # 2. Copiar dados convertendo banco para string
    connection.execute(
        sa.text("""
            INSERT INTO financials_temp 
            (id, profile_id, banco, agencia, conta, tipo_conta, cpf_cnpj, 
             tipo_chave_pix, chave_pix, preferencia, created_at, updated_at)
            SELECT id, profile_id, printf('%03d', banco), agencia, conta, tipo_conta, 
                   cpf_cnpj, tipo_chave_pix, chave_pix, preferencia, created_at, updated_at
            FROM financials
        """)
    )
    
    # 3. Remover tabela original
    op.drop_table('financials')
    
    # 4. Renomear tabela temporária
    op.rename_table('financials_temp', 'financials')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Para SQLite, precisamos recriar a tabela completa
    connection = op.get_bind()
    
    # 1. Criar tabela temporária com estrutura original
    op.create_table('financials_temp',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('profile_id', sa.Integer(), sa.ForeignKey('profiles.id'), nullable=False),
        sa.Column('banco', sa.Integer(), nullable=False),
        sa.Column('agencia', sa.String(length=10), nullable=False),
        sa.Column('conta', sa.String(length=15), nullable=False),
        sa.Column('tipo_conta', sa.String(length=20), nullable=False),
        sa.Column('cpf_cnpj', sa.String(length=20), nullable=False),
        sa.Column('tipo_chave_pix', sa.String(length=20), nullable=False),
        sa.Column('chave_pix', sa.String(length=50), nullable=False),
        sa.Column('preferencia', sa.String(length=10), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now())
    )
    
    # 2. Copiar dados convertendo banco para integer
    connection.execute(
        sa.text("""
            INSERT INTO financials_temp 
            (id, profile_id, banco, agencia, conta, tipo_conta, cpf_cnpj, 
             tipo_chave_pix, chave_pix, preferencia, created_at, updated_at)
            SELECT id, profile_id, CAST(banco AS INTEGER), agencia, conta, tipo_conta, 
                   cpf_cnpj, tipo_chave_pix, chave_pix, preferencia, created_at, updated_at
            FROM financials
        """)
    )
    
    # 3. Remover tabela original
    op.drop_table('financials')
    
    # 4. Renomear tabela temporária
    op.rename_table('financials_temp', 'financials')
    
    # ### end Alembic commands ### 