"""corrigir_tipo_coluna_status_para_enum

Revision ID: fac0bf1cfd90
Revises: 131c5fdf2f57
Create Date: 2025-07-24 09:49:06.094838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fac0bf1cfd90'
down_revision = '131c5fdf2f57'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('space_event_types', 'status',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('space_event_types', 'status',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    # ### end Alembic commands ### 