# Módulo de implementações dos repositórios
from .user_repository_impl import UserRepositoryImpl
from .role_repository_impl import RoleRepositoryImpl
from .profile_repository_impl import ProfileRepositoryImpl
from .artist_type_repository_impl import ArtistTypeRepositoryImpl
from .musical_style_repository_impl import MusicalStyleRepositoryImpl
from .artist_repository_impl import ArtistRepositoryImpl 